-- ===========================================
-- CINEVERSE DATABASE SETUP
-- Chạy file này trong Supabase SQL Editor
-- ===========================================

-- 1. TẠO BẢNG PROFILES
-- ===========================================
create table if not exists public.profiles (
    id uuid not null primary key references auth.users(id) on delete cascade,
    username text not null unique,
    created_at timestamp with time zone default now()
);

alter table public.profiles enable row level security;

-- Policies cho profiles
create policy "Enable read access for all users"
on public.profiles for select
to anon, authenticated
using (true);

create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = id));

create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));

-- 2. TẠO BẢNG WATCHLIST
-- ===========================================
create table if not exists public.watchlist (
    user_id uuid not null references auth.users(id) on delete cascade,
    id integer not null,
    type text not null check (type in ('movie','tv')),
    adult boolean not null,
    backdrop_path text,
    poster_path text,
    release_date date not null,
    title text not null,
    vote_average numeric(4,1) not null,
    created_at timestamp with time zone not null default now(),
    primary key (user_id, id, type)
);

alter table public.watchlist enable row level security;

-- Policies cho watchlist
create policy "Users can view their own watchlist"
on public.watchlist for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));

create policy "Users can insert their own watchlist"
on public.watchlist for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));

create policy "Users can delete their own watchlist"
on public.watchlist for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));

-- 3. TẠO BẢNG HISTORIES
-- ===========================================
create table if not exists public.histories (
    user_id uuid not null references auth.users(id) on delete cascade,
    id bigint generated by default as identity primary key,
    media_id integer not null,
    type text not null check (type in ('movie','tv')),
    season integer not null default 0,
    episode integer not null default 0,
    duration double precision not null default 0,
    last_position double precision not null default 0,
    completed boolean not null default false,
    adult boolean not null,
    backdrop_path text,
    poster_path text,
    release_date date not null,
    title text not null,
    vote_average numeric(4,1) not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (user_id, media_id, type, season, episode)
);

-- Index cho histories
create index if not exists histories_user_updated_idx
on public.histories (user_id, updated_at desc);

alter table public.histories enable row level security;

-- Policies cho histories
create policy "Users can view their own histories"
on public.histories for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));

create policy "Users can insert their own histories"
on public.histories for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));

create policy "Users can update their own histories"
on public.histories for update
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id))
with check ((( SELECT auth.uid() AS uid) = user_id));

create policy "Users can delete their own histories"
on public.histories for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));

-- 4. TẠO FUNCTION AUTO-UPDATE updated_at
-- ===========================================
create or replace function public.set_updated_at()
returns trigger
set search_path = ''
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- Trigger cho histories
drop trigger if exists set_updated_at on public.histories;
create trigger set_updated_at
before update on public.histories
for each row
execute function public.set_updated_at();

-- ===========================================
-- HOÀN THÀNH! 
-- Các bảng đã được tạo:
-- - profiles: Lưu thông tin user
-- - watchlist: Danh sách theo dõi
-- - histories: Lịch sử xem
-- ===========================================
