-- Migration: Add CineVerse Tables to Remote Database
-- This migration ensures all CineVerse tables exist on remote Supabase

-- Create profiles table if not exists
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid not null primary key references auth.users(id) on delete cascade,
    username text not null unique,
    created_at timestamp with time zone default now()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create watchlist table if not exists
CREATE TABLE IF NOT EXISTS public.watchlist (
    user_id uuid not null references auth.users(id) on delete cascade,
    id integer not null,
    type text not null check (type in ('movie','tv')),
    adult boolean not null,
    backdrop_path text,
    poster_path text,
    release_date date not null,
    title text not null,
    vote_average numeric(4,1) not null,
    created_at timestamp with time zone not null default now(),
    primary key (user_id, id, type)
);

-- Enable RLS
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;

-- Create histories table if not exists
CREATE TABLE IF NOT EXISTS public.histories (
    user_id uuid not null references auth.users(id) on delete cascade,
    id bigint generated by default as identity primary key,
    media_id integer not null,
    type text not null check (type in ('movie','tv')),
    season integer not null default 0,
    episode integer not null default 0,
    duration double precision not null default 0,
    last_position double precision not null default 0,
    completed boolean not null default false,
    adult boolean not null,
    backdrop_path text,
    poster_path text,
    release_date date not null,
    title text not null,
    vote_average numeric(4,1) not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (user_id, media_id, type, season, episode)
);

-- Create index for histories
CREATE INDEX IF NOT EXISTS histories_user_updated_idx
ON public.histories (user_id, updated_at desc);

-- Enable RLS
ALTER TABLE public.histories ENABLE ROW LEVEL SECURITY;

-- Create function for auto-updating updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
SET search_path = ''
LANGUAGE plpgsql
AS $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- Create trigger for histories
DROP TRIGGER IF EXISTS set_updated_at ON public.histories;
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.histories
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Policies for profiles
DROP POLICY IF EXISTS "Enable read access for all users" ON public.profiles;
CREATE POLICY "Enable read access for all users"
ON public.profiles FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile"
ON public.profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile"
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Policies for watchlist
DROP POLICY IF EXISTS "Users can view their own watchlist" ON public.watchlist;
CREATE POLICY "Users can view their own watchlist"
ON public.watchlist FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own watchlist" ON public.watchlist;
CREATE POLICY "Users can insert their own watchlist"
ON public.watchlist FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own watchlist" ON public.watchlist;
CREATE POLICY "Users can delete their own watchlist"
ON public.watchlist FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Policies for histories
DROP POLICY IF EXISTS "Users can view their own histories" ON public.histories;
CREATE POLICY "Users can view their own histories"
ON public.histories FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own histories" ON public.histories;
CREATE POLICY "Users can insert their own histories"
ON public.histories FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own histories" ON public.histories;
CREATE POLICY "Users can update their own histories"
ON public.histories FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own histories" ON public.histories;
CREATE POLICY "Users can delete their own histories"
ON public.histories FOR DELETE
TO authenticated
USING (auth.uid() = user_id);