import { TVChannel } from "./types";

// Danh sách các kênh TV Việt Nam và quốc tế
export const vietnamChannels: TVChannel[] = [
  // VTV
  {
    id: "vtv1",
    name: "VTV1",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/3/32/VTV1_logo_2013.svg/200px-VTV1_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV1.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv2",
    name: "VTV2",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/VTV2_logo_2013.svg/200px-VTV2_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV2.m3u8",
    type: "hls",
    category: "education",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv3",
    name: "VTV3",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/b/b7/VTV3_logo_2013.svg/200px-VTV3_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV3.m3u8",
    type: "hls",
    category: "entertainment",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv4",
    name: "VTV4",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/VTV4_logo_2013.svg/200px-VTV4_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV4.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv5",
    name: "VTV5",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/f/fc/VTV5_logo_2013.svg/200px-VTV5_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV5.m3u8",
    type: "hls",
    category: "entertainment",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv6",
    name: "VTV6",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/VTV6_logo_2013.svg/200px-VTV6_logo_2013.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV6.m3u8",
    type: "hls",
    category: "kids",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv7",
    name: "VTV7",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/e/e1/VTV7_logo_2016_final.svg/200px-VTV7_logo_2016_final.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV7.m3u8",
    type: "hls",
    category: "education",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv8",
    name: "VTV8",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/6/6f/VTV8_logo_2017.svg/200px-VTV8_logo_2017.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV8.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtv9",
    name: "VTV9",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/f/fb/VTV9_logo_2017.svg/200px-VTV9_logo_2017.svg.png",
    url: "https://vtv1-token.vtvdigital.vn/live/VTV9.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  // HTV
  {
    id: "htv7",
    name: "HTV7",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/f/f7/HTV7_logo.svg/200px-HTV7_logo.svg.png",
    url: "https://live.htv.com.vn/htv/HTV7.m3u8",
    type: "hls",
    category: "entertainment",
    country: "VN",
    quality: "HD",
  },
  {
    id: "htv9",
    name: "HTV9",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/d/df/HTV9_logo.svg/200px-HTV9_logo.svg.png",
    url: "https://live.htv.com.vn/htv/HTV9.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  // THVL
  {
    id: "thvl1",
    name: "THVL1",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/7/77/THVL1_logo.svg/200px-THVL1_logo.svg.png",
    url: "https://thvli.vn/thvl1hd.m3u8",
    type: "hls",
    category: "entertainment",
    country: "VN",
    quality: "HD",
  },
  {
    id: "thvl2",
    name: "THVL2",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/6/6e/THVL2_logo.svg/200px-THVL2_logo.svg.png",
    url: "https://thvli.vn/thvl2hd.m3u8",
    type: "hls",
    category: "entertainment",
    country: "VN",
    quality: "HD",
  },
  // VTC
  {
    id: "vtc1",
    name: "VTC1",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/3/3b/VTC1_logo_2019.svg/200px-VTC1_logo_2019.svg.png",
    url: "https://live.vtc.vn/vtc1.m3u8",
    type: "hls",
    category: "news",
    country: "VN",
    quality: "HD",
  },
  {
    id: "vtc3",
    name: "VTC3 - Thể thao",
    logo: "https://upload.wikimedia.org/wikipedia/vi/thumb/a/a4/VTC3_logo_2019.svg/200px-VTC3_logo_2019.svg.png",
    url: "https://live.vtc.vn/vtc3.m3u8",
    type: "hls",
    category: "sports",
    country: "VN",
    quality: "HD",
  },
];

// Kênh quốc tế (Demo streams)
export const internationalChannels: TVChannel[] = [
  {
    id: "nasa",
    name: "NASA TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/200px-NASA_logo.svg.png",
    url: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    type: "hls",
    category: "documentary",
    country: "US",
    quality: "HD",
  },
  {
    id: "france24-en",
    name: "France 24 (EN)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/France_24_logo.svg/200px-France_24_logo.svg.png",
    url: "https://live.france24.com/hls/live/2009216/France24_EN/master.m3u8",
    type: "hls",
    category: "news",
    country: "FR",
    quality: "HD",
  },
  {
    id: "dw",
    name: "DW News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/DW_News_Logo_2021.svg/200px-DW_News_Logo_2021.svg.png",
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    type: "hls",
    category: "news",
    country: "DE",
    quality: "HD",
  },
  {
    id: "euronews",
    name: "Euronews",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Euronews_2016_logo.svg/200px-Euronews_2016_logo.svg.png",
    url: "https://euronews.akamaized.net/hls/live/2027421/euronews-en/index.m3u8",
    type: "hls",
    category: "news",
    country: "EU",
    quality: "HD",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera English",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Aljazeera_eng.svg/200px-Aljazeera_eng.svg.png",
    url: "https://live-hls-web-aje.getaj.net/AJE/index.m3u8",
    type: "hls",
    category: "news",
    country: "QA",
    quality: "HD",
  },
  {
    id: "nhk-world",
    name: "NHK World Japan",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/NHK_World-Japan_Logo.svg/200px-NHK_World-Japan_Logo.svg.png",
    url: "https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index.m3u8",
    type: "hls",
    category: "news",
    country: "JP",
    quality: "HD",
  },
  {
    id: "bloomberg",
    name: "Bloomberg TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Bloomberg_logo.svg/200px-Bloomberg_logo.svg.png",
    url: "https://bloomberg-bloomberg-1-eu.plex.tv/live/240/hls/live-large/main.m3u8",
    type: "hls",
    category: "news",
    country: "US",
    quality: "HD",
  },
  {
    id: "rt",
    name: "RT News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/RT_logo.svg/200px-RT_logo.svg.png",
    url: "https://rt-glb.rttv.com/live/rtnews/playlist.m3u8",
    type: "hls",
    category: "news",
    country: "RU",
    quality: "HD",
  },
  {
    id: "cgtn",
    name: "CGTN",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/CGTN.svg/200px-CGTN.svg.png",
    url: "https://news.cgtn.com/resource/live/english/cgtn-news.m3u8",
    type: "hls",
    category: "news",
    country: "CN",
    quality: "HD",
  },
];

// Demo streams cho testing
export const demoStreams: TVChannel[] = [
  {
    id: "bbb",
    name: "Big Buck Bunny",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/220px-Big_buck_bunny_poster_big.jpg",
    url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    type: "hls",
    category: "movies",
    country: "Demo",
    quality: "HD",
  },
  {
    id: "sintel",
    name: "Sintel",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Sintel_poster.jpg/220px-Sintel_poster.jpg",
    url: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8",
    type: "hls",
    category: "movies",
    country: "Demo",
    quality: "HD",
  },
  {
    id: "tears",
    name: "Tears of Steel",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Tears_of_Steel_poster.jpg/220px-Tears_of_Steel_poster.jpg",
    url: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    type: "hls",
    category: "movies",
    country: "Demo",
    quality: "HD",
  },
];

// Tất cả kênh
export const allChannels: TVChannel[] = [
  ...vietnamChannels,
  ...internationalChannels,
  ...demoStreams,
];
